# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1543819907);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1543820027);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1543819374);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1543819614);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1543819494);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1543819303);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migrated-sync-button", true);
user_pref("browser.migration.version", 56);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.preferences.defaultPerformanceSettings.enabled", false);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1543819310983");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1543822910983");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181104094137");
user_pref("browser.startup.homepage", "http://ipinfo.io/json");
user_pref("browser.startup.homepage_override.buildID", "20181104094137");
user_pref("browser.startup.homepage_override.mstone", "56.2.5");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"e10s-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"dta-manager-button\",\"home-button\",\"ublock0_raymondhill_net-browser-action\",\"_75afe46a-7a50-4c6b-b866-c43a1075b071_-browser-action\",\"user-agent-switcher_ninetailed_ninja-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\",\"_75afe46a-7a50-4c6b-b866-c43a1075b071_-browser-action\",\"user-agent-switcher_ninetailed_ninja-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20181203);
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("distribution.hawkeye116477.bookmarksProcessed", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 22);
user_pref("extensions.dta.network.http.max-connections", 0);
user_pref("extensions.dta.version", "3.0");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.e10sMultiBlockedByAddons", true);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181104094137");
user_pref("extensions.lastAppVersion", "56.2.5");
user_pref("extensions.lastPlatformVersion", "56.2.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"uBlock0@raymondhill.net\":\"f1945728-b2be-4493-a0e0-1c94a85e0c86\",\"user-agent-switcher@ninetailed.ninja\":\"1931356e-cdb1-446f-a799-81b548654fee\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("layers.acceleration.disabled", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1543819311);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181104094137");
user_pref("media.gmp-manager.lastCheck", 1543819307);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.webrtc.debug.log_file", "/tmp/WebRTC.log");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1543819873);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.key.menuAccessKeyFocuses", false);
